const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const RESET = "RESET";
const INCREMENT_BY_COUNT = "INCREMENT_BY_COUNT";
const DECREMENT_BY_COUNT = "DECREMENT_BY_COUNT";

export { INCREMENT, DECREMENT, RESET, INCREMENT_BY_COUNT, DECREMENT_BY_COUNT };
