export const API_URL_GET_TODOS = "http://localhost:5174/api/v1/todos/get";

export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILD = "GET_TODOS_FAILD";

export const REVERSE_TODOS = "REVERSE_TODOS";
export const REVERSE_DELETED_TODOS = "REVERSE_DELETED_TODOS";

export const GET_DELETED_TODOS_REQUEST = "GET_DELETED_TODOS_REQUEST";
export const GET_DELETED_TODOS_SUCCESS = "GET_DELETED_TODOS_SUCCESS";
export const GET_DELETED_TODOS_FAILD = "GET_DELETED_TODOS_FAILD";
